log_level: info

# if fail_open is true, the server will allow traffic even if the threat source is not available
# if fail_open is false, the server will block traffic if the threat source is not available
fail_open: true

AbuseIPDB:
  enabled: true
  api_key: "YOUR_API_KEY_HERE"
  expiration_time: 24h
  confidence_score_threshold: 50 # if the confidence score is greater than this threshold, the IP is considered a threat
  cache_max_size: 1000 # maximum number of entries in the cache